<?php
namespace Teacher\Controller;
use Think\Controller;
class ContentController extends Controller {
    public function courseSelection(){
    	$user=$_SESSION[user];
    	$Course=M('Course');
    	$where['teacherID']=$user;
    	$list=$Course->where($where)->select();
    	$Login=M('Login');
    	$courseIDs=$Login->select();
    	for($i=0;$i<count($list);$i++){
    		//获取选该课程学生数
    		$cishu=0;
    		//获取选该课程学生学号
    		$stuID="";
    		for($j=0;$j<count($courseIDs);$j++){
    			//thinkphp中数据库中字段名只是小写
    			$arr=explode(",",$courseIDs[$j][courseid]);
    			if(in_array($list[$i][id],$arr)){
    				$cishu++;
    				if($stuID==""){
    					$stuID=$courseIDs[$j][user];
    				}else{
    					$stuID=$stuID.",".$courseIDs[$j][user];
    				}
    			}
    			$list[$i][count1]=$cishu;
    			$list[$i][stuID]=$stuID;
    		}
    	}
    	$this->assign('list',$list);
    	$this->display();
    }
    public function courseDetail(){
    	$courseId=I('post.courseId');
    	$stuid=I('post.stuid');
    	$stuIdArr=explode(",",$stuid);
    	$stuDetail=[];
    	$Course=M('Course');
    	$data[id]=$courseId;
    	$room=$Course->where($data)->getField('plan');
    	$len=strpos($room,"班");
    	$room=substr($room,0,$len);
    	$Login=M('Login');
    	for($i=0;$i<count($stuIdArr);$i++){
    		$where[user]=$stuIdArr[$i];
    		$list=$Login->where($where)->find();
    		$list[room]=$room;
    		$stuDetail[]=$list;
    	}
    	//利用学号进行排序
    	for($i=0;$i<count($stuDetail)-1;$i++){
    		for($j=$i+1;$j<count($stuDetail);$j++){
    			if($stuDetail[$i][user]>$stuDetail[$j][user]){
    				$haha=$stuDetail[$i];
    				$stuDetail[$i]=$stuDetail[$j];
    				$stuDetail[$j]=$haha;
    			}
    		}
    	}
    	$this->ajaxReturn($stuDetail);
    }
    //录入成绩
    public function grade(){
    	$user=$_SESSION[user];
    	$Course=M('Course');
    	$where['teacherID']=$user;
    	$list=$Course->where($where)->select();
    	$Login=M('Login');
    	$courseIDs=$Login->select();
    	for($i=0;$i<count($list);$i++){
    		//获取选该课程学生学号
    		$stuID="";
    		for($j=0;$j<count($courseIDs);$j++){
    			//thinkphp中数据库中字段名只是小写
    			$arr=explode(",",$courseIDs[$j][courseid]);
    			if(in_array($list[$i][id],$arr)){
    				if($stuID==""){
    					$stuID=$courseIDs[$j][user];
    				}else{
    					$stuID=$stuID.",".$courseIDs[$j][user];
    				}
    			}
    			$list[$i][stuID]=$stuID;
    		}
    	}
    	$this->assign('list',$list);
    	$this->display();
    }
    //渲染给成绩的学生表格
    public function gradeDetail(){
    	$user=$_SESSION[user];
    	$courseId=I('post.courseid');
    	$stuid=I('post.stuid');
    	$stuIdArr=explode(",",$stuid);
    	//判断有无该成绩数据表
    	$tabelName='edu_grade'.$courseId;
    	$databaseName="education";
    	$tabel=M();
    	$result1=$tabel->query("SELECT * FROM information_schema.tables WHERE table_schema = '{$databaseName}' AND table_name = '{$tabelName}'");
		
    	if($result1){
    		$Grade=M('Grade'.$courseId);
    		$list2=$Grade->select();
    		for($i=0;$i<count($list2);$i++){
    			$list2[$i]['courseId']=$courseId;
    		}
    	}else{	
    	//获取课程名
    	$Course=M('Course');
    	$where['id']=$courseId;
    	$kecheng=$Course->where($where)->find();
    	//获取老师姓名
    	$Login=M('Login');
    	$where1['user']=$user;
    	$teacher=$Login->where($where1)->getField('name');
    	$xueshengArr=[];
    	for($i=0;$i<count($stuIdArr);$i++){
    		$where1['user']=$stuIdArr[$i];
    		$list=$Login->where($where1)->find();
    		$list['courseName']=$kecheng['name'];
    		$list['courseId']=$kecheng['id'];
    		$list['teacher']=$teacher;
    		$xueshengArr[]=$list;
    	}
    	//利用学号进行排序
    	for($i=0;$i<count($xueshengArr)-1;$i++){
    		for($j=$i+1;$j<count($xueshengArr);$j++){
    			if($xueshengArr[$i][user]>$xueshengArr[$j][user]){
    				$haha=$xueshengArr[$i];
    				$xueshengArr[$i]=$xueshengArr[$j];
    				$xueshengArr[$j]=$haha;
    			}
    		}
    	}
    	    		    		
    		//获取该课程的选课冲突字段
    		$level=$kecheng['level'];
    		//删除课程表里该条课程记录
    		$Course->where('id='.$courseId)->delete();
    		//删除学生关联的该条课程记录
    		for($i=0;$i<count($stuIdArr);$i++){
    			$xueshengResult=$Login->where('user='.$stuIdArr[$i])->find();
    			$xueshengCourseL=$xueshengResult['coursel'];
    			$courseIds=$xueshengResult['courseid'];
    			$xueshengCourseLArr=explode(',',$xueshengCourseL);
    			$courseIdsArr=explode(',',$courseIds);
    			$levelArr=explode(",",$level);
//  			$haha=array_diff($xueshengCourseLArr,$levelArr);
				$haha=array();
				for($k=0;$k<count($xueshengCourseLArr);$k++){
					for($j=0;$j<count($levelArr);$j++){
						if($xueshengCourseLArr[$k]==$levelArr[$j]){
							break;
						}
						if($j==count($levelArr)-1){
							$haha[]=$xueshengCourseLArr[$k];
						}
					}
				}
//  			$hehe=array_diff($courseIdsArr,$courseId1);
				$hehe=array();
				for($q=0;$q<count($courseIdsArr);$q++){
					if($courseIdsArr[$q]==$courseId){
						
					}else{
						$hehe[]=$courseIdsArr[$q];
					}
				}
    			$str1=implode(",",$haha);
    			$str2=implode(",",$hehe);
    			if($gradeId){
    				$gradeId=$gradeId.",".$courseId;
    			}else{
    				$gradeId=$courseId;
    			}
    			$data10['courseL']=$str1;
    			$data10['courseID']=$str2;
    			$data10['gradeId']=$courseId;
    			$Login->where('user='.$stuIdArr[$i])->save($data10);
    			}
    	
    	//创建数据表
    		$t=M();
    		$result2=$t->execute("CREATE TABLE `{$databaseName}`.`{$tabelName}` ( `id` INT(10) NOT NULL AUTO_INCREMENT , `user` VARCHAR(255) NOT NULL , `name` VARCHAR(255) NOT NULL , `pingshi` FLOAT(50) NOT NULL , `qizhong` FLOAT(50) NOT NULL , `shijian` FLOAT(50) NOT NULL , `qimo` FLOAT(50) NOT NULL , `profession` VARCHAR(255) NOT NULL , `grade` FLOAT(50) NOT NULL , `teacher` VARCHAR(255) NOT NULL , `courseName` VARCHAR(255) NOT NULL , PRIMARY KEY (`id`)) ENGINE = MyISAM CHARACTER SET utf8 COLLATE utf8_general_ci");
//  	//把结果同时赋给数据表
			$tableName='Grade'.$courseId;
    	$Grade=M($tableName);
    	for($i=0;$i<count($xueshengArr);$i++){
    		$graArr['user']=$xueshengArr[$i]['user'];
    		$graArr['name']=$xueshengArr[$i]['name'];
    		$graArr['profession']=$xueshengArr[$i]['zhuanye'];
    		$graArr['teacher']=$xueshengArr[$i]['teacher'];
    		$graArr['courseName']=$xueshengArr[$i]['courseName'];
    		$graArr['pingshi']=0;
    		$graArr['qizhong']=0;
    		$graArr['shijian']=0;
    		$graArr['qimo']=0;
    		$graArr['grade']=0;
    		$Grade->data($graArr)->add();
    	}
    	$list2=$Grade->select();
    	for($i=0;$i<count($list2);$i++){
    			$list2[$i]['courseId']=$courseId;
    		}

    	}
    	$this->ajaxReturn($list2);
    }
   public function addGrade(){
   	$id=I("post.id");
   	$ziduan=I("post.ziduan");
   	$courseId=I("post.courseId");
   	$value1=I("post.value1");
   	$value2=I("post.value2");
   	$Grade=M("Grade".$courseId);
   	$data['grade']=$value2;
   	$data[$ziduan]=$value1;
   	$where['id']=$id;
   	$Grade->where($where)->save($data);
   }

}